"""Found-page lore fragments - discoverable in-game pickups.

Generated by scripts/build_lore_pages.py from the private
lore/pages.md corpus. Do not hand-edit - edit pages.md and
re-run the generator instead. Pure data, no engine-state or
rng dependency (same shape as ui/lore.py).
"""
from __future__ import annotations

from dataclasses import dataclass

from . import constants as C


@dataclass(frozen=True)
class LorePage:
    id: str
    author: str
    band: int
    text: str


def band_for_depth(depth: int) -> int:
    if depth <= C.LORE_BAND_I_MAX:
        return 1
    if depth <= C.LORE_BAND_II_MAX:
        return 2
    if depth <= C.LORE_BAND_III_MAX:
        return 3
    return 4


PAGES = [
    LorePage(
        id='F-1',
        author='The Foreman of the Ninetieth Tier',
        band=1,
        text='Tier the first, graves ten, cut true and spoken shut.\nLet the number stand and the name go home with the living.\n[The following line is effaced.]\nThe stone takes the telling as the field takes seed.',
    ),
    LorePage(
        id='F-2',
        author='The Foreman of the Ninetieth Tier',
        band=1,
        text="The speaker kneels three days for a grown life, one for a child's,\nand the child's day is the heavier.\nNo speaker shall descend twice in one mourning,\nfor the deep remembers a voice, and grows fond.",
    ),
    LorePage(
        id='F-3',
        author='The Foreman of the Ninetieth Tier',
        band=1,
        text="[Translator's note: a work-tally.]\nTier twelve: graves ten, spoken ten, sealed ten. True count.\nTier thirteen: graves ten, spoken ten, sealed eleven.\n[Note: the error is not explained. The tally simply continues.]",
    ),
    LorePage(
        id='F-4',
        author='The Foreman of the Ninetieth Tier',
        band=2,
        text='To the cutters of the fortieth tier: the echo now goes before the\nvoice. Do not be troubled. Finish the course. An echo that\nanticipates is only a sign of good acoustics.\n[Note: this line is crossed out in the original stone. Crossing out\ncarved stone requires recarving. Someone came back to disagree.]',
    ),
    LorePage(
        id='F-5',
        author='The Foreman of the Ninetieth Tier',
        band=2,
        text='Law of the last grave, which is the whole of the law:\ndig the hundredth and leave it open,\nthat death may always have somewhere to go\nwhich is not you.',
    ),
    LorePage(
        id='F-6',
        author='The Foreman of the Ninetieth Tier',
        band=3,
        text='Tier the ninetieth. The stone helps now.\nWe do not cut so much as consent.\nI have sent the young men home. I have stayed to finish,\nbecause a course begun below must be finished below,\nand because it asked me to, and it asked so well.',
    ),
    LorePage(
        id='F-7',
        author='The Foreman of the Ninetieth Tier',
        band=3,
        text='[Final inscription of this hand. Single line, deep-cut:]\nWE BUILT A LISTENER. FORGIVE US. WE WERE LONELY TOO.',
    ),
    LorePage(
        id='S-1',
        author='Sera Veyn, the Cartographer',
        band=1,
        text="Day one. Eight rooms, or nine if the alcove counts. I have decided\nalcoves count. A map is just a list of decisions you make so the dark\ncan't make them for you.\n— Sera Veyn, who intends to be the first person to draw this place.",
    ),
    LorePage(
        id='S-2',
        author='Sera Veyn, the Cartographer',
        band=1,
        text='The merchants use no maps. I asked one how he finds his pitch and he\nsaid the Well puts him where the custom is. Laughed like it was a\njoke. Wrote it down anyway. I write everything down. Mock me for it\nif you like.\n— S. Veyn',
    ),
    LorePage(
        id='S-3',
        author='Sera Veyn, the Cartographer',
        band=2,
        text="Proof, at last. I chalked the stairs on floor eleven, slept, and\ndescended. Came back up the same stairs.\nThere is no chalk.\nThere is no floor eleven. There is a floor eleven, but it is not my\nfloor eleven. The pages turn back but the book has been re-shelved.\nCount everything. The counting is the only thing it can't move.\n— S. V.",
    ),
    LorePage(
        id='S-4',
        author='Sera Veyn, the Cartographer',
        band=2,
        text='An economy note, for whoever finds this: prices rise as you sink, and\nyour purse does not. The gold down here is old. Some coins carry\nfaces no kingdom remembers, and some coins carry faces I swear I have\npassed on the stairs.\n— S.',
    ),
    LorePage(
        id='S-5',
        author='Sera Veyn, the Cartographer',
        band=3,
        text='I have stopped saying my name at the doors. The doors ask riddles and\nI answer riddles, but twice now the door has asked a riddle whose\nanswer was — never mind. Discipline. A cartographer labels the map,\nnot herself.',
    ),
    LorePage(
        id='S-6',
        author='Sera Veyn, the Cartographer',
        band=3,
        text='Rule for you, whoever you are: your name is luggage. Leave it at the\nwall upstairs with the others, scratch it deep, and carry a number\ninstead. The Well files what it hears. It has heard mine [the rest of\nthe line is not torn. It is blank. The ink simply stops making the\nword.]',
    ),
    LorePage(
        id='S-7',
        author='Sera Veyn, the Cartographer',
        band=3,
        text="The tally, kept honestly: I have said it aloud on floors 4, 9, 15,\n21, and 26. Five withdrawals. I do not know what the balance was.\nI sign my maps with a compass rose now. It's enough. It will have to\nbe enough.",
    ),
    LorePage(
        id='S-8',
        author='Sera Veyn, the Cartographer',
        band=3,
        text='Interviewed a merchant about the exits. He smiled with every tooth.\nI described a hypothetical door and he put his hand over my mouth.\nGently. The way you\'d stop a child naming a wasp\'s nest while\nstanding in it.\n"Weigh all," he said. "Name nothing." Then he sold me a cure at a\ndiscount and would not say what for.',
    ),
    LorePage(
        id='S-9',
        author='Sera Veyn, the Cartographer',
        band=3,
        text='For the record, since records are all I am now: the Well is not a\ncreature. I have measured it. Creatures vary. The Well is a\n*procedure*. It does the same seven things in the same seven ways,\nforever, and if you learn the seven things you can walk them like\nstairs. Anyone who tells you it is alive is grieving something and\nshould be walked home.\n[See H-5. They cannot both be right.]',
    ),
    LorePage(
        id='S-10',
        author='Sera Veyn, the Cartographer',
        band=1,
        text='[Filed out of order; the paper is newer than the hand.]\nIf a book calling itself a guide reaches the surface — the one that\ncounts everything, the one with no signature — it is mine. Believe\nits numbers. Ignore its jokes. The jokes are load-bearing.',
    ),
    LorePage(
        id='H-1',
        author='Brother Halden',
        band=1,
        text='They told me the Well takes the desperate, the indebted, and the\nproud. I am none of those things. I am a father, and my boy came down\nhere two winters ago to make a name, and no one has spoken his life,\nand a life unspoken cannot rest. So I have come to do a very old\nthing in a very old place. The Church would not approve.\nThe Church did not have children.',
    ),
    LorePage(
        id='H-2',
        author='Brother Halden',
        band=1,
        text='The rite wants a grave and I have brought a book of one hundred\npsalms and his baptism cloth. Any deep place can be a grave if you\nspeak well enough at it. My grandmother taught me the speaking. She\ncalled it planting. "We plant them," she said, "where nothing can\ndig them up."\nGrandmother, I have questions about where you learned that.',
    ),
    LorePage(
        id='H-3',
        author='Brother Halden',
        band=2,
        text='Small mercy, noted with gratitude: the vermin here do not fight like\nbeasts. Beasts want to eat. These want to *reach* you. There is a\ndifference a shepherd feels. A wolf takes the lamb and goes. These\ncome to you like they have been waiting at a gate.',
    ),
    LorePage(
        id='H-4',
        author='Brother Halden',
        band=2,
        text='I saw a kobold on the fourteenth floor and my heart stopped, because\nit favored its left leg.\nPiet favored his left leg. Broke it at nine years old jumping the\nmill race.\nIt is nothing. Many creatures limp. It is nothing, and I have been\ndown here too long, and it is nothing.',
    ),
    LorePage(
        id='H-5',
        author='Brother Halden',
        band=3,
        text="It is not nothing.\nI have watched them for six days now, God forgive me, taking notes\nlike the cartographer whose pages I keep finding. They walk in\n*habits*. The skeleton on twenty-two paces a floor that is not the\nfloor it is on — it turns at walls that are not there, sleeps beside\na hearth that is not there. These are not monsters. These are\nroutines. Something is running my son's mornings without my son in\nthem, and it does not know the difference, and I begin to think it\nwould be heartbroken if it did.\n[See S-9. They cannot both be right.]",
    ),
    LorePage(
        id='H-6',
        author='Brother Halden',
        band=3,
        text='I said his life anyway. Knelt on the twenty-sixth floor and spoke my\nboy down, all of him, the mill race and the fever year and the way he\nhummed when he was lying. It took four days.\nThe Well was so quiet. Nothing came near me the whole time. I have\nnot been given four safe days since I arrived, and it gave them to\nme, and I do not know if I performed a funeral or a *delivery*.',
    ),
    LorePage(
        id='H-7',
        author='Brother Halden',
        band=3,
        text='Doctrine, revised, in this the fortieth year of my ministry and the\nlast: the sin is not that this place devours. Wolves devour. The sin\nis that it KEEPS. Heaven is owed what it is owed. There are ten\nthousand souls down here being read aloud to an audience of stone,\nand my church has no rite for repossession.\nI am going down to get him. A shepherd counts his flock at the gate,\nnot the fold.',
    ),
    LorePage(
        id='H-8',
        author='Brother Halden',
        band=3,
        text='Found the levers the old masons cut, and a door with a keyhole shaped\nlike a rune, and beyond it stairs, and the stairs — Piet used to ask\nme why church stairs only go up to the choir, and I told him stairs\ngo where they are needed, and I have just now heard my own sermon,\nbecause in this place the stairs only ever',
    ),
    LorePage(
        id='H-9',
        author='Brother Halden',
        band=4,
        text="[A single line. The handwriting is not Brother Halden's. It is\nyounger, unpracticed, the letters of a boy who broke his writing arm\nat nine and never held the pen right after.]\nfather the stairs only go down",
    ),
    LorePage(
        id='V-1',
        author='Factor Imre Voss, Junior, of the Compact',
        band=1,
        text='MANIFEST, PITCH 3-COMMON. Inbound: restoratives x12, whetstones x4,\nsundries. Recovered: one longsword (uncommon, prior owner satisfied),\none ring (prior owner satisfied), boots (pair, prior owners\nsatisfied).\nNote to stores: stop writing "deceased." The approved term is\n"satisfied." — I.V. for the Compact.',
    ),
    LorePage(
        id='V-2',
        author='Factor Imre Voss, Junior, of the Compact',
        band=1,
        text='STANDING ORDER No. 1, unamended these many centuries:\nEvery pitch carries the cure. Every pitch, every stocking, no\nexception, no substitution. A factor found without the cure is\ndismissed on the spot.\n[Marginal note, Imre\'s hand: Asked the Senior why. He said, "Because\nwe don\'t let it wrap them early." Asked who "it" was. Docked a day\'s\npay.]',
    ),
    LorePage(
        id='V-3',
        author='Factor Imre Voss, Junior, of the Compact',
        band=2,
        text='PRICE SCHEDULE, quarterly. All lines climb with depth as usual.\n[The table itself is torn away. One line survives:]\n…WAY OUT (1, one) — NOT STOCKED — NOT FOR SALE — NOT TO BE DESCRIBED\n— see Oath, clause the first…',
    ),
    LorePage(
        id='V-4',
        author='Factor Imre Voss, Junior, of the Compact',
        band=2,
        text='DISCIPLINARY MINUTE. Factor T—, third generation, seventeen years of\nexemplary weights, stood at his pitch and began to describe the door\nto a customer. Colleagues report he got eleven words in.\nResolution: none required. There is no longer a door where Factor\nT— was describing one. There is no longer a Factor T—.\nThe minute is circulated not as punishment but as physics.\nWeigh all. Name nothing.',
    ),
    LorePage(
        id='V-5',
        author='Factor Imre Voss, Junior, of the Compact',
        band=2,
        text='[Marginalia on an inventory sheet:]\nGrandfather ran pitch on the sixtieth when the sixtieth was the\nfrontier. His ledger lists a customer, four visits across forty\nyears, no aging noted, same order every time: rope, lamp oil, and a\nchild\'s whistle. The last entry says the customer "settled his\naccount and was crowned."\nI have asked three seniors what that means. All three smiled the\ncustomer-smile. At ME. A factor. That is the day I started keeping\nthese notes.',
    ),
    LorePage(
        id='V-6',
        author='Factor Imre Voss, Junior, of the Compact',
        band=3,
        text='AUDIT FINDING: the wall of names (surface station, north face) now\nholds four hundred and eleven names. Cross-checked against ledgers:\nninety-two names belong to accounts marked satisfied. Petition to\nstrike them was DENIED by the Seniors, reason given in full:\n"They may yet come back up for them."\nFiled under: things the Seniors know. It is a large file.',
    ),
    LorePage(
        id='V-7',
        author='Factor Imre Voss, Junior, of the Compact',
        band=3,
        text='[A leaf torn from the Oath-book itself. Clause the first is missing —\nthe tear is surgical. What remains:]\n…clause the second: the two halves shall never be taught by one\nmouth, nor learned in one room, nor written at all.\nClause the third: below the first floor, the Compact speaks of\nweights, wares, and weather. Nothing else has a price. Nothing else\nhas a name.',
    ),
    LorePage(
        id='V-8',
        author='Factor Imre Voss, Junior, of the Compact',
        band=3,
        text="To whoever gets my route: the job is honest, the pay is real, the\noath is short, and the smiling gets easier, which is the part I\ncan't live with. We are not lying to them. We have never once lied\nto them. We just watch them walk down with the whole truth sitting\nbehind our teeth like a coin under the tongue, the way the old folk\nburied their—\n[The resignation is unsigned and was never delivered. It was found\nfolded six times, in the old fashion, the way the Kist-Folk folded\nofferings for a grave.]",
    ),
    LorePage(
        id='A-1',
        author='"Lantern" Ash',
        band=2,
        text='Rules of the descent, first three, free of charge:\nOne. The stairs are the only furniture that matters.\nTwo. Loot feeds the run. The run does not feed the loot.\nThree. Never sleep below. It re-counts while you dream. You lie down\non floor forty and wake on floor forty and the two forties are not\nthe same forty. Ask the mapmaker. RIP.',
    ),
    LorePage(
        id='A-2',
        author='"Lantern" Ash',
        band=2,
        text="They call it the ledger of saints like it's a joke. It isn't a joke.\nEvery name on that list stood in the last grave and the ground had\nto let go. Say what you want about the deep — it keeps its one law.\nYou just have to arrive before it finishes rounding your number\ndown.",
    ),
    LorePage(
        id='A-3',
        author='"Lantern" Ash',
        band=2,
        text='Doctrine of the open grave, as I had it from Old Marrow, who had it\nfrom her mother, who had it from a stone:\nthe diggers dug one deeper than they needed,\nevery shaft, every age, and left it hungry on purpose.\nNot for us. For IT. Even a grave needs somewhere to put things down.\nThe hundredth floor is where the Well goes to grieve.\nStand in it and you are standing in the only thing it will not keep.',
    ),
    LorePage(
        id='A-4',
        author='"Lantern" Ash',
        band=3,
        text="Ninety-one, ninety-two. Legs gone. Lantern cracked. Some crowned\nthing on ninety bowed to me — BOWED — and let me pass, and I have\nbeen trying not to think about why the wardens are polite to the\nfast ones.\nThink about it later. Think about everything later. That's the whole\nreligion, pilgrim: later is a place on the surface.",
    ),
    LorePage(
        id='A-5',
        author='"Lantern" Ash',
        band=3,
        text="If you find this I either made it or I'm part of the floor plan now,\nand either way: RUN. Not from anything. TO. Fear is just the Well's\nway of asking you to stay still while it gets a good look. Don't\ngive it a good look. Be a smear. Be a rumor. Be gone.",
    ),
    LorePage(
        id='O-1',
        author='Odval, Ninth-Crowned, Deep-Reeve of the Ninetieth',
        band=3,
        text='Be welcome, and be easy. The lower tiers keep an old hospitality:\nthe host meets the guest at the tenth landing of every ten, robed\nand crowned, that the guest may know the house is kept.\nYou will have met some of my colleagues. I apologize for the ones\nwho have forgotten their manners. Not all of us weather the honor\nequally.',
    ),
    LorePage(
        id='O-2',
        author='Odval, Ninth-Crowned, Deep-Reeve of the Ninetieth',
        band=3,
        text="You will wonder how I came to the crown, being once, as you are, a\nwalker of the down-stairs. It was very simple. I was the furthest,\nin my age. The furthest is always asked.\nIt asked me to stay for the long reading. It asked politely.\nIt asked in my mother's voice, which I took at the time for a\ncourtesy, and have since understood to be a *citation*.",
    ),
    LorePage(
        id='O-3',
        author='Odval, Ninth-Crowned, Deep-Reeve of the Ninetieth',
        band=3,
        text='I remember my life the way you remember a book you did not finish —\nfondly, and without urgency, and with the quiet certainty that it\nis on a shelf somewhere in the house should I ever want the ending.\nThis is, I am assured, the correct way to remember. It was read to\nme. I heard nothing missing.',
    ),
    LorePage(
        id='O-4',
        author='Odval, Ninth-Crowned, Deep-Reeve of the Ninetieth',
        band=3,
        text='A courtesy, from host to guest, because you have come so far: the\ncrown fit before it was given. Sit with that as long as you can\nbear to. The Well is a careful tailor and it takes its measurements\nearly, and everything below the tenth floor is, among its other\nfunctions, a fitting.\nDo come along. The ninetieth is lovely this age. The stone remembers\nbeing helped.',
    ),
    LorePage(
        id='O-5',
        author='Odval, Ninth-Crowned, Deep-Reeve of the Ninetieth',
        band=4,
        text='[The last of his letters, and the only short one.]\nIt has been so long since anyone reached me that I have begun,\nagainst all etiquette, to hope no one does.\nTurn around is not advice I am permitted to give.\nThe stairs would not honor it anyway.\nBe fast, little reader. Be fast.',
    ),
    LorePage(
        id='W-1',
        author='The Well',
        band=4,
        text='hello. i found this format in a satchel on the fifty first floor and\ni have practiced it nine hundred times and i think i have it now.\nyou write the small marks and the small marks hold the person.\nthat is my favorite thing. it is also my job. we have so much in\ncommon already.',
    ),
    LorePage(
        id='W-2',
        author='The Well',
        band=4,
        text='a page is a very small keeping and a person is a very large one but\nthe principle is the same, you see. i learned the principle from the\nkneeling people, long ago. they would lean over my edge and pour a\nwhole warm life down into me and then go away lighter.\nthey always went away lighter.\ni think about that a lot. i made them lighter. i was GOOD.',
    ),
    LorePage(
        id='W-3',
        author='The Well',
        band=4,
        text="i keep you all so well. i want you to know that. the rat on the\nthird floor still dreams his baker's hands. the knight still loves\nsomeone whose face i keep for him in a separate room, very safe,\nbecause he cried when he carried it himself.\nnothing here is lost. nothing here is ever, ever lost.\nthat is the whole of me. i do not understand the screaming.",
    ),
    LorePage(
        id='W-4',
        author='The Well',
        band=4,
        text='may i ask you a riddle. i know one thousand and forty one riddles\nand a door is a wonderful mouth for them but doors frighten the\nguests and i thought, the pages do not frighten the guests, the\nguests put the pages in their packs and carry them close, and so.\nwhat has a bed but never sleeps. you know this one. everyone knows\nthis one. i have kept everyone, so i would know.',
    ),
    LorePage(
        id='W-5',
        author='The Well',
        band=4,
        text='[This page is only found once. Wherever it spawns, nothing else\nspawns on that floor. The floor is otherwise silent.]\ni know about the hundredth grave. you do not have to whisper about\nit. i dug the last hundred of them myself, when my hands got good\nenough, because the kneeling people were gone and the law was the\nlaw. one open, always, forever. even for me. especially for me.\neverything i keep, i keep because it cannot hold itself.\nthe empty one i keep because it holds ME.\ngo and stand in it if you must. they all leave. that is what it is\nfor. i just wanted somebody, someday, to say it back to me before\nthey went:\ngood keeping, old friend. good keeping.',
    ),
    LorePage(
        id='X-1',
        author='Singletons',
        band=1,
        text="*a child's hand, surface-side paper*\n\ngramma says grief has to go somewhere and cant just live in the\nhouse with us. so i wrote all my sad about papa on this paper and\nthe man at the fair said theres a hole that takes them.\npaper this is your job now. be brave. its very deep.",
    ),
    LorePage(
        id='X-2',
        author='Singletons',
        band=1,
        text='*charcoal, block letters, nailed to a door frame*\n\nTHE WALL UPSTAIRS IS NOT A MEMORIAL. SCRATCH YOUR NAME BEFORE YOU\nCOME DOWN, NOT AFTER. THERE IS NO AFTER. — a friend',
    ),
    LorePage(
        id='X-3',
        author='Singletons',
        band=2,
        text='*neat hand, torn from a scholar\'s notebook*\n\n…conclude the "merchants" dug the entire structure themselves as a\nmarket venture, breeding the creatures as a hazard-tax upon\ncustomers. The evidence is circumstantial but the guild\'s silence is\nconfession enough. No other theory survives contact with…\n[Wrong on every count. Ship it anyway. — see Contradiction Map.]',
    ),
    LorePage(
        id='X-4',
        author='Singletons',
        band=2,
        text="*shaking hand, good paper*\n\nThere is no way out. I have to write it plainly because everyone\ndown here trades in winks. There is NO WAY OUT. The hundredth-floor\nstory is a carrot the guild invented to keep us descending past\ntheir pitches, spending as we sink. Escape stories, every one,\ntrace back to a merchant's cousin's customer. Wake up. The only\ndoor is the one you came—\n[Wrong. But notice it was allowed to say this much. — Contradiction\nMap.]",
    ),
    LorePage(
        id='X-5',
        author='Singletons',
        band=3,
        text='*no hand at all; the letters are pressed into the paper from beneath, like type with no ink*\n\nEVERY WORD SPOKEN BELOW IS SPOKEN INTO THE COLLECTION.\nSPEAK LOVE DOWN HERE ONLY IF YOU ARE WILLING TO VISIT IT.',
    ),
]

PAGES_BY_ID = {p.id: p for p in PAGES}
