"""Regenerates engine/lorepages.py from the private lore/pages.md corpus.

lore/ is gitignored and private (see lore/TRUTH.md) - this script only
needs to run on a machine that has it (i.e. the author's). The OUTPUT,
engine/lorepages.py, contains nothing but the found-page id/author/band/
text data itself (exactly what pages.md calls "written now, wired in
later") - no meta-commentary, no Contradiction Map, no ARG notes, and
excludes the two fragments pages.md reserves for the ARG (A-6, X-6).

    python3 scripts/build_lore_pages.py
"""
from __future__ import annotations

import os
import re

GAME_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES_MD = os.path.join(GAME_DIR, "lore", "pages.md")
OUT_PATH = os.path.join(GAME_DIR, "engine", "lorepages.py")

EXCLUDED_IDS = {"A-6", "X-6"}  # reserved for the ARG - see pages.md

AUTHOR_DISPLAY = {
    "THE FOREMAN OF THE NINETIETH TIER": "The Foreman of the Ninetieth Tier",
    "SERA VEYN, THE CARTOGRAPHER": "Sera Veyn, the Cartographer",
    "BROTHER HALDEN": "Brother Halden",
    "FACTOR IMRE VOSS, JUNIOR, OF THE COMPACT": "Factor Imre Voss, Junior, of the Compact",
    '"LANTERN" ASH': '"Lantern" Ash',
    "ODVAL, NINTH-CROWNED, DEEP-REEVE OF THE NINETIETH": "Odval, Ninth-Crowned, Deep-Reeve of the Ninetieth",
    "THE WELL": "The Well",
    "SINGLETONS": "Singletons",
}

BAND_WORDS = {"I": 1, "II": 2, "III": 3, "IV": 4}

HEADING_RE = re.compile(r"^\*\*([A-Z]+-\d+) — Band (IV|III|II|I)\*\*(.*)$")


def parse(text: str):
    lines = text.splitlines()
    pages = []
    author = None
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("## "):
            heading = line[3:].strip()
            if heading == "CONTRADICTION MAP":
                break  # everything after here is meta-commentary, not fragments
            author = AUTHOR_DISPLAY.get(heading, heading.title())
            i += 1
            continue
        m = HEADING_RE.match(line)
        if m and author:
            page_id, band_word, rest = m.groups()
            band = BAND_WORDS[band_word]
            i += 1
            # An optional italic descriptor (physical-medium flavor note)
            # follows the heading, e.g. "— *a child's hand, surface-side
            # paper*" - occasionally wrapped across a second source line
            # (X-5), so keep consuming lines until the closing '*'.
            descriptor = None
            rest = rest.strip()
            if rest.startswith("— *"):
                desc_parts = [rest[3:]]
                while not desc_parts[-1].rstrip().endswith("*") and i < len(lines):
                    desc_parts.append(lines[i])
                    i += 1
                descriptor = " ".join(desc_parts).rstrip()
                if descriptor.endswith("*"):
                    descriptor = descriptor[:-1]
            quote_lines = []
            while i < len(lines) and lines[i].startswith(">"):
                content = lines[i][1:]
                if content.startswith(" "):
                    content = content[1:]
                quote_lines.append(content)
                i += 1
            body = "\n".join(quote_lines)
            if descriptor:
                body = f"*{descriptor}*\n\n{body}"
            if page_id not in EXCLUDED_IDS:
                pages.append((page_id, author, band, body))
            continue
        i += 1
    return pages


def render(pages) -> str:
    out = [
        '"""Found-page lore fragments - discoverable in-game pickups.\n\n'
        "Generated by scripts/build_lore_pages.py from the private\n"
        "lore/pages.md corpus. Do not hand-edit - edit pages.md and\n"
        "re-run the generator instead. Pure data, no engine-state or\n"
        'rng dependency (same shape as ui/lore.py).\n"""\n'
        "from __future__ import annotations\n\n"
        "from dataclasses import dataclass\n\n"
        "from . import constants as C\n\n\n"
        "@dataclass(frozen=True)\n"
        "class LorePage:\n"
        "    id: str\n"
        "    author: str\n"
        "    band: int\n"
        "    text: str\n\n\n"
        "def band_for_depth(depth: int) -> int:\n"
        "    if depth <= C.LORE_BAND_I_MAX:\n"
        "        return 1\n"
        "    if depth <= C.LORE_BAND_II_MAX:\n"
        "        return 2\n"
        "    if depth <= C.LORE_BAND_III_MAX:\n"
        "        return 3\n"
        "    return 4\n\n\n"
        "PAGES = [\n"
    ]
    for page_id, author, band, body in pages:
        out.append(
            "    LorePage(\n"
            f"        id={page_id!r},\n"
            f"        author={author!r},\n"
            f"        band={band!r},\n"
            f"        text={body!r},\n"
            "    ),\n"
        )
    out.append("]\n\n")
    out.append("PAGES_BY_ID = {p.id: p for p in PAGES}\n")
    return "".join(out)


def main():
    with open(PAGES_MD, "r", encoding="utf-8") as f:
        text = f.read()
    pages = parse(text)
    assert len(pages) == 54, f"expected 54 shippable pages, parsed {len(pages)}"
    ids = [p[0] for p in pages]
    assert len(ids) == len(set(ids)), "duplicate page ids parsed"
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(render(pages))
    print(f"wrote {OUT_PATH}: {len(pages)} pages")


if __name__ == "__main__":
    main()
